services:
    twig.extension.date:
       class: Twig_Extensions_Extension_Date
       tags:
            - { name: twig.extension }
    
    locale_subscriber:
        class: BlogBundle\EventSubscriber\LocaleSubscriber
        arguments: ['%kernel.default_locale%']
        tags: 
            - { name: kernel.event_subscriber }

    admin.category:
        class: BlogBundle\Admin\CategoryAdmin
        arguments: [~, BlogBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category, group: "Gestion du blog" }

    admin.post:
        class: BlogBundle\Admin\PostAdmin
        arguments: [~, BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post, group: "Gestion du blog" }

    admin.comment:
        class: BlogBundle\Admin\CommentAdmin
        arguments: [~, BlogBundle\Entity\Comment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Comment, group: "Gestion du blog" }
        